### ISSUE TITLE
SingletonPerKey disposing per request in Aspnet

### ISSUE THREAD

**Issue by stephenlautier** [ipjohnson/Grace#256]
Hi,

It seems that when registering a service as `SingletonPerKey`, and the service implements `IDisposable` in aspnet core, it disposes per request, however instance is created only once.

Execution flow is as follows
- First request > initialize service (ctor) > *execute* > call `.Dispose()`
- Second request > *execute* > call `.Dispose()`

This is what i got
```cs
scope.Configure(c =>
{
	c.Export<DataClientManager>().As<IDataClientManager>().Lifestyle.SingletonPerKey((scope, context) => "global");
});

public interface IDataClientManager
{
	IDataClientManager Register(object type);
}

public class DataClientManager : IDataClientManager, IDisposable
{
	private readonly HashSet<object> _instances = new HashSet<object>();

	public IDataClientManager Register(object type)
	{
		_instances.Add(type);
		return this;
	}

	public void Dispose()
	{
	}
}
```

This causes some services such as GQL to not work properly, as they will `Dispose` and next time round it will blow.

I expects that it only Dispose once the server shuts down in the case of singleton

### Versions
- Grace 7.1.0
- Grace.AspNetCore.Hosting: 7.0.1
- NetcoreApp 2.2

I have a working sample as well if needed. Thanks!

**Comment by ipjohnson** [comment]
I agree it should dispose only at when the host is disposed.  Can you email me the sample and I'll take a look at tonight or tomorrow morning.

**Comment by stephenlautier** [comment]
Its available here https://github.com/sketch7/dotnet.multitenancy/tree/feature/initial-imp (this branch)
- git clone https://github.com/sketch7/dotnet.multitenancy.git --branch feature/initial-imp --depth 1
- Run `Sketch7.Multitenancy.Sample.Api`
- Execute request
```
curl --location --request GET 'http://localhost:5001/api/heroes' \
--header 'Content-Type: application/json' \
--header 'X-SSV-Tenant: hots'
```

#### Interesting points:
- https://github.com/sketch7/dotnet.multitenancy/blob/5d84a55c9ece729b2281d86a8b8a7c2ffb6090e7/samples/Sketch7.Multitenancy.Sample.Api/Startup.cs
- https://github.com/sketch7/dotnet.multitenancy/blob/feature/initial-imp/samples/Sketch7.Multitenancy.Sample.Api/Heroes/HeroDataClient.cs#L78
- https://github.com/sketch7/dotnet.multitenancy/blob/feature/initial-imp/samples/Sketch7.Multitenancy.Sample.Api/Heroes/DataClientManager.cs#L23

**Comment by ipjohnson** [comment]
I was able to reproduce this and I'll have some time next week to release a fix. For the next couple days you could try marking the export as externally owned `.ExternallyOwned()` and it will keep it from being disposed (ever).

**Comment by ipjohnson** [comment]
Ok I have a fix for it, essentially the wrong disposal context was being used. I've released a new pre-release let me know how it works out for you.

**Comment by stephenlautier** [comment]
Can you confirm if this one only I need to update `Grace: 7.1.1-RC793`?

**Comment by stephenlautier** [comment]
After updating to the mentioned version `7.1.1-RC793`, SingletonPerKey as my usage isn't working anymore. Basically can't get the data from `.GetExtraData` from either scope/context inorder to resolve the tenant

**Comment by ipjohnson** [comment]
Ok I pushed a newer version and tested it with your repo. Usually the scope & disposal scope should be the same so that you don't get data from a child scope but in your case you actually do need the data from the child scope.

**Comment by stephenlautier** [comment]
Thanks I retested it again, however its partially solved. In my example the `IDataClientManager` is not being disposed but the service implementing `IHeroDataClient` e.g. `MockHotsHeroDataClient` its still being disposed as it was.

Further more I retested the actual scenario (e.g. GQL) and it still happens that the Schema is being disposed

**Comment by ipjohnson** [comment]
As we’ve talked about this over email and it’s resolved I’m going to close this out. If you have any other issues let me know
